Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Awesome security group
      SecurityGroupIngress:
        # Allow SSH from everywhere
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        # Allow ICMP destination unreachable for TCP PMTU discovery to work properly
        - IpProtocol: icmp
          FromPort: 3
          ToPort: 4
          CidrIp: 0.0.0.0/0

